spring:
  application:
    name: domain

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    password: guest
    username: guest
    virtual-host: /

rabbitmq:
  queues:
    created-products: createdProducts
    updated-products: updatedProducts
    deleted-products: deletedProducts

grpc:
  server:
    port: ${GRPC_SERVER_PORT}

server:
  port: 8082
