spring:
  application:
    name: gateway

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    password: guest
    username: guest
    virtual-host: /

  jackson:
    serialization:
      fail-on-empty-beans: false

rabbitmq:
  queues:
    created-products: createdProducts
    updated-products: updatedProducts
    deleted-products: deletedProducts

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

grpc:
  server:
    host: ${GRPC_SERVER_HOST}
    port: ${GRPC_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    enable:
      all: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

logging:
  level:
    org.springframework.web: INFO
    io.micrometer.core: DEBUG

server:
  port: 8080